name: ecommerceapp
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

#--------------------------dependencies--------------------------#
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # state management
  get: ^4.6.5
  get_storage: ^2.1.1

  # product platform_specific:

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  android_12:
    image: assets/logos/luna-store-splash-logo-white.png
    image_dark: assets/logos/luna-store-splash-logo-black.png
  android: true
  ios: true
  web: false


#  color: "#FFFFFF"
#  color_dark: "#272727"
#  image: assets/logos/luna-store-splash-logo-black-removebg-preview.png
#  image_dark: assets/logos/luna-store-splash-logo-white-removebg-preview.png





  #-------------------------- ./ packages end --------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  #-------------------------- local assets --------------------------#
  assets:
    - assets/logos/
    - assets/images/onboarding_images/
    - assets/images/animations/sammy-Line-workout.gif
    - assets/images/animations/sammy-line-sale.png
    - assets/images/animations/sammy-Line-success.png
    - assets/images/animations/sammy-line-come-back-later.png
    - assets/images/animations/sammy-Line-man-receives-a-mail.png
    - assets/images/animations/sammy-Line-travel-backpack-with-passport-and-air-ticket.gif
    - assets/logos/
    - assets/icons/categories/icons8-sports-48.png
    - assets/icons/categories/icons8-t-shirt-50.png
    - assets/icons/categories/icons8-pair-of-sneakers-50.png
    - assets/icons/categories/icons8-cosmetics-50.png
    - assets/icons/categories/icons8-heart-with-dog-paw-50.png
    - assets/icons/categories/icons8-toy-50.png
    - assets/icons/categories/icons8-furniture-50.png
    - assets/icons/categories/icons8-sparkling-diamond-50.png
    - assets/icons/categories/icons8-electronics-50.png
    - assets/images/banners/banner-1.jpg
    - assets/images/banners/banner-2.avif
    - assets/images/banners/banner-3.jpg

  #-------------------------- local fonts --------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800



