name: ecommerceapp
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

#--------------------------dependencies--------------------------#
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # state management
  get: ^4.6.5
  get_storage: ^2.1.1

  # product platform_specific:

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  android_12:
    image: assets/logos/luna-store-splash-logo-white.png
    image_dark: assets/logos/luna-store-splash-logo-black.png
  android: true
  ios: true
  web: false


#  color: "#FFFFFF"
#  color_dark: "#272727"
#  image: assets/logos/luna-store-splash-logo-black-removebg-preview.png
#  image_dark: assets/logos/luna-store-splash-logo-white-removebg-preview.png





  #-------------------------- ./ packages end --------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  #-------------------------- local assets --------------------------#
  assets:
    - assets/logos/
    - assets/images/onboarding_images/
    - assets/images/animations/
    - assets/logos/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/nike-shoes.png
    - assets/images/products/nike-shoes.png
    - assets/images/products/product-jacket.png
    - assets/images/products/product-jeans.png
    - assets/images/products/product-shirt.png
    - assets/images/products/product-slippers.png
    - assets/images/products/nike-air-redandblack.png
    - assets/images/products/nike-air-orange.jpg
    - assets/images/products/nike-air-white-magenta.webp
    - assets/images/products/nike-air-white and red.jpg
    - assets/images/products/ssmsung-s23-mobile.jpg
    - assets/images/products/samsung-s23-mobile-white-back.png
    - assets/images/products/samsung-s23-back.webp
    - assets/images/products/Apple_iPhone-13-Pro_iPhone-13-Pro-Max.jpg
    - assets/images/products/Iphone-13-pro-max-back.jpg
    - assets/images/products/iphone-13-pro-max-dual-side.jpg
    - assets/images/products/apple-iphone-13-pro-max-front.png
    - assets/images/products/toni-dogfood.png
    - assets/images/products/nike air jordar 4 single blue.jpg
    - assets/images/products/nike air jordar 4 single orange.jpg
    - assets/images/products/nike air max.webp
    - assets/images/products/nike backetball shoe green black.webp
    - assets/images/products/nike wild horse.jpg
    - assets/images/products/track-suit-black.jpg
    - assets/images/products/track-suit-blue.jpg
    - assets/images/products/track suit red.jpg
    - assets/images/products/track-suit-parrot-green.jpg
    - assets/images/products/adidas-football.jpg
    - assets/images/products/baseball-bat.jpg
    - assets/images/products/criket-bat.jpg
    - assets/images/products/tennis-racket.webp
    - assets/images/products/bedroom-bed.jpg
    - assets/images/products/bedroom-lamp.jpg
    - assets/images/user/user-image.png
    - assets/icons/brands/nike-icon.png


  #-------------------------- local fonts --------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800



